DROP DATABASE IF EXISTS gruppo40;

CREATE DATABASE gruppo40;
USE gruppo40;

CREATE TABLE Users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	username VARCHAR(20) NOT NULL,
	password VARCHAR(50) NOT NULL,
	
	PRIMARY KEY(id)
);

CREATE TABLE Users_Data (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(40) NOT NULL,
	surname VARCHAR(40) NOT NULL,
	half_year_max_sells INT UNSIGNED NOT NULL,
	user_id INT UNSIGNED NOT NULL,
	
	PRIMARY KEY(id),
	FOREIGN KEY (user_id) REFERENCES Users(id)
);

CREATE TABLE Brands (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(30),
	
	PRIMARY KEY(id)
);

CREATE TABLE Types (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(30),
	
	PRIMARY KEY(id)
);
	
CREATE TABLE Radios (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	brand INT UNSIGNED NOT NULL,
	type INT UNSIGNED NOT NULL,
	size INT UNSIGNED NOT NULL,
	color VARCHAR(20) NOT NULL,
	optional VARCHAR(20),
	antenna VARCHAR(20) NOT NULL,
	
	PRIMARY KEY(id),
	FOREIGN KEY (brand) REFERENCES Brands(id),
	FOREIGN KEY (type) REFERENCES Types(id)
);

CREATE TABLE Sells (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	num_radio INT UNSIGNED NOT NULL,
	date TIMESTAMP NOT NULL,
	price DOUBLE NOT NULL, 
    user_id INT UNSIGNED NOT NULL,
    radio_id INT UNSIGNED NOT NULL,
    
    PRIMARY KEY(id),
    FOREIGN KEY (user_id) REFERENCES Users(id),
   	FOREIGN KEY (radio_id) REFERENCES Radios(id)
);
